apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Enables application status badge feature
  statusbadge.enabled: "true"

  repositories: |
    - url: https://github.com/yysu/hiskio-gitops-argocd-manifest.git
    - url: https://github.com/yysu/hiskio-gitops-demo-manifest.git
